"""Canonical Hilm Alnada storefront catalog and booking rules.

Source basis: the uploaded Hilm Alnada catalog PDF. The storefront, cashier and
management surfaces should consume this canonical structure rather than duplicate
service/pricing data. Prices below follow the catalog where legible; entries marked
`catalog_note` preserve catalog wording/conditions instead of inventing missing data.
"""

from dataclasses import dataclass
from typing import Dict, Tuple

CATALOG_SECTIONS: Tuple[str, ...] = (
    "hair",
    "makeup",
    "eyebrows",
    "lashes",
    "lips",
    "nails",
    "facial",
    "manicure_pedicure",
    "hair_removal",
    "massage",
    "relaxation_room",
    "celebration_room",
    "coffee_lounge",
    "tailoring",
    "offers",
)

SERVICE_CATALOG: Dict[str, Tuple[dict, ...]] = {
    "hair": (
        {"name": "تسريحة شعر بوي", "price": 100},
        {"name": "تسريحة شعر للرقبة", "price": 150},
        {"name": "تسريحة شعر للكتف", "price": 200},
        {"name": "تسريحة شعر لنصف الظهر", "price": 250},
        {"name": "تسريحة شعر لنهاية الظهر", "price": 300},
        {"name": "تسريحة شعر مع تركيب اكستنشن", "price": 300},
        {"name": "ضفيرة", "price": 150},
        {"name": "قص بوي", "price": 50},
        {"name": "قص للرقبة", "price": 50},
        {"name": "قص أطفال", "price": 45},
        {"name": "قص أطراف", "price": 30},
        {"name": "قص غرة", "price": 30},
        {"name": "قص تدريج", "price": 30},
        {"name": "استشوار بوي", "price": 50},
        {"name": "استشوار للرقبة", "price": 60},
        {"name": "استشوار للكتف", "price": 70},
        {"name": "استشوار لنصف الظهر", "price": 100},
        {"name": "استشوار طول لنهاية الظهر", "price": 150},
        {"name": "صبغة لون واحد شعر بوي", "price": 170},
        {"name": "صبغة لون واحد شعر للرقبة", "price": 200},
        {"name": "صبغة لون واحد شعر للكتف", "price": 350},
        {"name": "صبغة لون واحد لنصف الظهر", "price": 400},
        {"name": "صبغة لون واحد جذور", "price": 150},
        {"name": "سحب لون شعر بوي", "price": 500},
        {"name": "سحب لون شعر للرقبة", "price": 600},
        {"name": "سحب لون شعر للكتف", "price": 700},
        {"name": "سحب لون لنصف الظهر", "price": 800},
        {"name": "سحب لون لشعر أسفل الظهر", "price": 1000},
        {"name": "سحب لون لنهاية الظهر", "price": 1200},
        {"name": "كونتور شعر", "price": 200},
        {"name": "جلسة ديتوكس لفروة الشعر", "price": 300},
        {"name": "فحص فروة", "price": 30},
        {"name": "هيد سبا", "price": 399},
        {"name": "بروتين جذور", "price": 500},
        {"name": "بروتين شعر قصير", "price": 500},
        {"name": "بروتين شعر وسط", "price": 600},
        {"name": "بروتين شعر طويل", "price": 780},
        {"name": "بروتين شعر طويل جداً", "price": 990},
        {"name": "بروتين شعر طويل وكثيف", "price": 1200},
        {"name": "جلوتين جذور", "price": 500},
        {"name": "جلوتين شعر قصير", "price": 590},
        {"name": "جلوتين شعر وسط", "price": 600},
        {"name": "جلوتين شعر طويل", "price": 800},
        {"name": "جلوتين شعر طويل جداً", "price": 1000},
        {"name": "جلوتين شعر طويل وكثيف", "price": 1190},
        {"name": "شامبو", "price": 150},
        {"name": "بلسم", "price": 150},
        {"name": "اكستنشن سيكر دائم 20 خصلة", "price": 1000},
        {"name": "اكستنشن سيكر دائم 40 خصلة", "price": 2000},
        {"name": "اكستنشن سيكر دائم 60 خصلة", "price": 3000},
        {"name": "صيانة اكستنشن سيكر دائم 20 خصلة", "price": 500},
        {"name": "صيانة اكستنشن سيكر دائم 40 خصلة", "price": 700},
        {"name": "صيانة اكستنشن سيكر دائم 60 خصلة", "price": 800},
        {"name": "فك اكستنشن + غسيل + معالجة + إعادة تركيب 20 خصلة", "price": 200},
        {"name": "فك اكستنشن + غسيل + معالجة + إعادة تركيب 40 خصلة", "price": 300},
        {"name": "فك اكستنشن + غسيل + معالجة + إعادة تركيب 60 خصلة", "price": 400},
    ),
    "makeup": (
        {"name": "ميك اب ناعم يومي", "price": 200},
        {"name": "ميك اب سهرة", "price": 350},
        {"name": "ميك اب مناسبات", "price": 450},
        {"name": "ميك اب عروس", "price": 800},
        {"name": "تجربة ميك اب", "price": 150},
        {"name": "تركيب رموش", "price": 80},
        {"name": "رموش مغناطيس", "price": 120},
        {"name": "تنظيف بشرة قبل المكياج", "price": 100},
        {"name": "خبرة + ميك اب", "price": 400},
        {"name": "لمسة سريعة", "price": 100},
        {"name": "تعليم مكياج جلسة واحدة", "price": 500},
    ),
    "eyebrows": (
        {"name": "حف حواجب", "price": 30},
        {"name": "صبغة حواجب", "price": 30},
        {"name": "تشقير حواجب", "price": 30},
        {"name": "رفع حواجب", "price": 150},
        {"name": "مايكرو بليدنج HAIRSTROKE", "price": 2000},
        {"name": "مايكرو بليدنج POWDER", "price": 2200},
        {"name": "مايكرو بليدنج OMBRE", "price": 2400},
        {"name": "مايكرو بليدنج BOLD COMBO", "price": 2600},
        {"name": "مايكرو بليدنج SOFT COMBO", "price": 2800},
        {"name": "مايكرو بليدنج 3D REALISTIC", "price": 3000},
    ),
    "lashes": (
        {"name": "رموش كلاسيك", "price": 299},
        {"name": "رموش هايبرد", "price": 300},
        {"name": "رموش مكس", "price": 350},
        {"name": "رموش سلك", "price": 350},
        {"name": "رموش روسية", "price": 400},
        {"name": "رموش فوليوم", "price": 400},
        {"name": "رموش طرف", "price": 250},
        {"name": "تنظيف رموش", "price": 50},
        {"name": "عكف الرموش YUMI", "price": 345},
        {"name": "عكف الرموش", "price": 200},
    ),
    "lips": (
        {"name": "توريد الشفاه", "price": 2100},
        {"name": "توريد بالليزر", "price": 2000},
        {"name": "جلسة تعزيز بعد شهرين", "price": 800},
        {"name": "جلسة تصحيح اللون", "price": 800},
        {"name": "إزالة تاتو الشفاه", "price": 1300},
        {"name": "إزالة تصبغات الشفاه", "price": 1500},
    ),
    "nails": (
        {"name": "هارد جل", "price": 400},
        {"name": "سوفت جل", "price": 300},
        {"name": "BIAB Gel", "price": 150},
        {"name": "ريفيل هارد جل", "price": 250},
        {"name": "ريفيل سوفت جل", "price": 150},
        {"name": "إزالة الجل", "price": 200},
        {"name": "إزالة لون الجل", "price": 50},
        {"name": "تركيب أكريليك كامل", "price": 350},
        {"name": "ريفيل أكريليك", "price": 250},
        {"name": "إزالة الأكريليك", "price": 120},
        {"name": "تركيب بوليجيل", "price": 320},
        {"name": "ريفيل بوليجيل", "price": 220},
        {"name": "إزالة بوليجيل", "price": 100},
    ),
    "facial": (
        {"name": "تنظيف بشرة للمراهقات", "price": 180},
        {"name": "تنظيف بشرة عميق", "price": 250},
        {"name": "تنظيف بشرة VIP", "price": 350},
        {"name": "كلاسيك فيشال", "price": 220},
        {"name": "ترطيب عميق", "price": 250},
        {"name": "فيشال الإشراقة", "price": 280},
        {"name": "أوكسجين فيشال", "price": 350},
        {"name": "هيدرافيشال", "price": 499},
        {"name": "فيشال حب الشباب", "price": 350},
        {"name": "فيشال البشرة الدهنية", "price": 320},
        {"name": "فيشال البشرة الحساسة", "price": 320},
        {"name": "فيشال التصبغات", "price": 450},
        {"name": "فيشال الكلف", "price": 450},
        {"name": "فيشال مكافحة التجاعيد", "price": 450},
        {"name": "فيتامين C فيشال", "price": 350},
        {"name": "كولاجين فيشال", "price": 399},
        {"name": "جولد فيشال", "price": 499},
        {"name": "درما بلانينغ", "price": 250},
        {"name": "درما بن", "price": 450},
        {"name": "ميزوثيرابي بدون إبر", "price": 450},
        {"name": "RF شد البشرة", "price": 399},
        {"name": "العلاج الضوئي LED", "price": 150},
        {"name": "هاي فريكونسي", "price": 120},
        {"name": "الموجات فوق الصوتية", "price": 180},
        {"name": "هيدروجين فيشال", "price": 550},
        {"name": "تنظيف بالأكسجين الجاف", "price": 300},
        {"name": "التقشير الكيميائي", "price": 380},
        {"name": "درما بن مع فيتامينات", "price": 400},
        {"name": "درما بن مع البلازما", "price": 450},
        {"name": "BB Glow", "price": 600},
        {"name": "كربوكسي ثيرابي", "price": 650},
        {"name": "ميزوثيرابي للوجه بالإبر", "price": 700},
    ),
    "manicure_pedicure": (
        {"name": "مانيكير كلاسيك", "price": 80},
        {"name": "مانيكير سبا", "price": 120},
        {"name": "مانيكير جل", "price": 150},
        {"name": "مانيكير فرنسي", "price": 150},
        {"name": "إزالة جل يدين", "price": 50},
        {"name": "برد وقص الأظافر", "price": 40},
        {"name": "تنظيف الجلد الزائد", "price": 40},
        {"name": "بارافين لليدين", "price": 80},
        {"name": "بديكير كلاسيك", "price": 100},
        {"name": "بديكير سبا", "price": 150},
        {"name": "بديكير جل", "price": 180},
        {"name": "بديكير علاجي", "price": 250},
        {"name": "إزالة جل قدمين", "price": 60},
        {"name": "إزالة الجلد الميت", "price": 60},
        {"name": "علاج تشققات الكعبين", "price": 120},
        {"name": "بارافين للقدمين", "price": 80},
    ),
    "hair_removal": (
        {"name": "حف حواجب", "price": 30},
        {"name": "حف الشنب", "price": 20},
        {"name": "حف الذقن", "price": 20},
        {"name": "حف الخدود", "price": 25},
        {"name": "حف الجبهة", "price": 20},
        {"name": "حف الرقبة", "price": 25},
        {"name": "الوجه كامل", "price": 80},
        {"name": "إبطين", "price": 60},
        {"name": "نصف الذراع", "price": 80},
        {"name": "الذراع كاملة", "price": 120},
        {"name": "البكيني", "price": 70},
        {"name": "الصدر", "price": 50},
        {"name": "نصف الظهر", "price": 60},
        {"name": "الظهر كامل", "price": 100},
        {"name": "الفخذين", "price": 120},
        {"name": "إزالة شعر بالليزر للوجه - الشفة العليا/الشنب", "price": 150},
        {"name": "إزالة شعر بالليزر للوجه - الذقن", "price": 150},
        {"name": "إزالة شعر بالليزر للوجه - الوجه", "price": 200},
        {"name": "إزالة شعر بالليزر للوجه - الرقبة", "price": 200},
        {"name": "إزالة شعر بالليزر للوجه - الوجه كامل", "price": 350},
        {"name": "جلسة تجربة منطقة واحدة", "price": 99},
    ),
    "massage": (
        {"name": "مساج كلاسيك", "price": 400, "duration_min": 60},
        {"name": "مساج سويدي", "price": 500, "duration_min": 60},
        {"name": "مساج أحجار ساخنة", "price": 550, "duration_min": 60},
        {"name": "مساج Deep Tissue", "price": 550, "duration_min": 60},
        {"name": "مساج حجامة", "price": 450, "duration_min": 60},
        {"name": "مساج بالزيوت العطرية", "price": 600, "duration_min": 60},
        {"name": "مساج للأزواج", "price": 800, "duration_min": 90},
        {"name": "مساج تايلندي", "price": 500, "duration_min": 60},
        {"name": "مساج رياضي", "price": 450, "duration_min": 60},
        {"name": "مساج الاسترخاء العميق", "price": 450, "duration_min": 60},
        {"name": "مساج الرأس والرقبة", "price": 250, "duration_min": 30},
        {"name": "مساج الظهر", "price": 250, "duration_min": 30},
        {"name": "مساج القدم", "price": 180, "duration_min": 30},
        {"name": "مساج اليدين", "price": 180, "duration_min": 30},
        {"name": "مساج الوجه", "price": 180, "duration_min": 30},
        {"name": "المساج التايلندي", "price": 250, "duration_min": 30},
    ),
    "relaxation_room": (
        {"name": "دخول غرفة الاسترخاء", "price": 50, "duration_min": 30},
        {"name": "دخول غرفة الاسترخاء", "price": 120, "duration_min": 60},
        {"name": "دخول غرفة الاسترخاء VIP", "price": 180, "duration_min": 90},
        {"name": "مشروب فاخر مع الضيافة", "price": 50},
        {"name": "ضيافة خاصة", "price": 80},
        {"name": "جلسة استرخاء مزدوجة", "price": 150},
        {"name": "تمديد الجلسة 30 دقيقة", "price": 50, "duration_min": 30},
        {"name": "تمديد الجلسة 60 دقيقة", "price": 80, "duration_min": 60},
        {"name": "حجز خصوصي للغرفة", "price": 100},
    ),
    "celebration_room": (
        {"name": "الباقة الأساسية", "price": 450},
        {"name": "الباقة المميزة", "price": 650},
        {"name": "الباقة الفاخرة", "price": 850},
        {"name": "حجز غرفة الاحتفالات بدون ضيافة", "price": 250, "duration_min": 60},
        {"name": "حجز غرفة الاحتفالات مع الضيافة", "price": 400, "duration_min": 60},
        {"name": "ديكور مناسبات أساسي", "price": 350},
        {"name": "ديكور مناسبات فاخر", "price": 600},
        {"name": "ديكور مخصص للتصوير", "price": 300},
        {"name": "ديكور مخصص حسب الفكرة", "catalog_note": "حسب الطلب"},
        {"name": "تصوير مناسبات صور", "price": 250, "duration_min": 30},
        {"name": "تصوير مناسبات صور", "price": 450, "duration_min": 60},
        {"name": "تصوير فيديو/ريلز/سوشيال ميديا", "price": 300, "duration_min": 30},
    ),
    "coffee_lounge": (
        {"name": "اسبريسو", "price": 18},
        {"name": "امريكانو", "price": 22},
        {"name": "كابتشينو", "price": 24},
        {"name": "لاتيه", "price": 24},
        {"name": "سبانش لاتيه", "price": 26},
        {"name": "فلات وايت", "price": 28},
        {"name": "شاي أسود", "price": 18},
        {"name": "شاي أخضر", "price": 20},
        {"name": "كرك", "price": 22},
        {"name": "شوكولاتة ساخنة", "price": 20},
        {"name": "آيس أمريكانو", "price": 20},
        {"name": "آيس لاتيه", "price": 24},
        {"name": "سبانش آيس لاتيه", "price": 26},
        {"name": "كراميل آيس لاتيه", "price": 26},
        {"name": "موكا آيس", "price": 26},
        {"name": "آيس تي خوخ", "price": 22},
        {"name": "آيس تي ليمون", "price": 22},
        {"name": "موهيتو ليمون ونعناع", "price": 24},
        {"name": "عصير برتقال طازج", "price": 24},
        {"name": "عصير ليمون بالنعناع", "price": 24},
        {"name": "مياه معدنية", "price": 18},
        {"name": "تشيز كيك", "price": 24},
        {"name": "كيك الشوكولاتة", "price": 22},
        {"name": "كيك الفانيلا", "price": 22},
        {"name": "كيك التمر", "price": 24},
        {"name": "تيراميسو", "price": 20},
        {"name": "براوني شوكولاتة", "price": 18},
        {"name": "كوكيز دبل شوكولاتة", "price": 18},
        {"name": "ميني بان كيك", "price": 20},
        {"name": "كريب شوكولاتة", "price": 24},
        {"name": "سلطة فواكه", "price": 18},
        {"name": "بيتزا مارغريتا", "price": 28},
        {"name": "بيتزا خضار", "price": 32},
        {"name": "بيتزا دجاج", "price": 34},
        {"name": "بيتزا رانش", "price": 36},
        {"name": "ميني ساندويتش دجاج", "price": 18},
        {"name": "ميني ساندويتش جبن", "price": 18},
        {"name": "بطاطس مقلية", "price": 16},
        {"name": "أصابع موزاريلا", "price": 16},
        {"name": "مكسرات", "price": 16},
    ),
    "tailoring": (
        {"name": "تعديل طول", "price": 35},
        {"name": "تقصير سحاب أو أزرار", "price": 40},
        {"name": "تعديل كم", "price": 50},
        {"name": "تعديل فستان بسيط", "price": 60},
        {"name": "تضييق أو توسيع فستان عادي", "price": 75},
        {"name": "تفصيل فستان عادي", "price": 120},
        {"name": "تفصيل عباية عادية", "price": 150},
        {"name": "تفصيل جلابية فاخرة", "price": 230},
        {"name": "تفصيل فستان تطريز فاخر", "price": 230},
        {"name": "تفصيل فستان فاخر", "price": 450},
        {"name": "ساعة خصر", "price_min": 130, "price_max": 170},
        {"name": "تقصير فخم", "price": 50},
        {"name": "تعديل جانبي", "price": 100},
        {"name": "تقصير أو تغيير سحاب", "price": 60},
        {"name": "تضييق بطانة", "price": 50},
        {"name": "خدمة عاجلة", "price": 80},
    ),
    "offers": (),
}


@dataclass(frozen=True)
class BookingRuleContract:
    every_booking_requires_start_time: bool = True
    booking_duration_required: bool = True
    end_time_is_derived_or_explicit: bool = True
    resource_conflict_check_required: bool = True
    employee_conflict_check_required: bool = True
    room_conflict_check_required_when_applicable: bool = True
    home_visit_travel_buffer_required: bool = True
    coffee_order_can_be_preordered_from_store: bool = True
    coffee_order_can_attach_to_booking: bool = True
    celebration_room_requires_time_slot: bool = True
    relaxation_room_requires_time_slot: bool = True
    offers_are_dynamic_and_separate_from_base_catalog: bool = True


CROSS_SELL_RULES = {
    "during_any_service_booking": (
        "offer_coffee_lounge_preorder",
        "offer_relaxation_room_when_timing_allows",
        "offer_celebration_room_when_context_suggests_occasion",
        "offer_relevant_active_offer_or_package",
    ),
    "before_checkout": (
        "show_selected_addons_with_time_impact",
        "recheck_availability_after_addons",
        "recalculate_total",
    ),
}


def booking_rule_contract() -> BookingRuleContract:
    return BookingRuleContract()
