from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class ProactiveEventStore:
    """Persistent Founder-facing events generated by real system changes.

    This store is separate from chat so important updates survive reloads and
    restarts. It stores summaries only, never raw credentials, commands, or
    approval identifiers.
    """

    def __init__(self, workspace_root: str | Path) -> None:
        root = Path(workspace_root).resolve()
        data_root = Path(os.getenv("AMEER_DATA_DIR") or (root / ".ameer"))
        data_root.mkdir(parents=True, exist_ok=True)
        self.path = data_root / "proactive_events.json"
        self.state_path = data_root / "proactive_state.json"
        self.data: Dict[str, Any] = {"events": []}
        self.state: Dict[str, Any] = {}
        self._load()

    def _load(self) -> None:
        try:
            parsed = json.loads(self.path.read_text(encoding="utf-8")) if self.path.exists() else {"events": []}
            self.data = parsed if isinstance(parsed, dict) and isinstance(parsed.get("events"), list) else {"events": []}
        except Exception:
            self.data = {"events": []}
        try:
            parsed_state = json.loads(self.state_path.read_text(encoding="utf-8")) if self.state_path.exists() else {}
            self.state = parsed_state if isinstance(parsed_state, dict) else {}
        except Exception:
            self.state = {}

    def _save(self) -> None:
        self.path.write_text(json.dumps(self.data, ensure_ascii=False, indent=2), encoding="utf-8")
        self.state_path.write_text(json.dumps(self.state, ensure_ascii=False, indent=2), encoding="utf-8")

    @staticmethod
    def _fingerprint(kind: str, title: str, summary: str, source: str) -> str:
        raw = "|".join((kind, title, summary, source)).encode("utf-8")
        return hashlib.sha256(raw).hexdigest()[:20]

    def emit(
        self,
        kind: str,
        title: str,
        summary: str,
        *,
        severity: str = "info",
        source: str = "ameer",
        evidence: Dict[str, Any] | None = None,
        dedupe_key: str | None = None,
    ) -> Dict[str, Any]:
        self._load()
        key = dedupe_key or self._fingerprint(kind, title, summary, source)
        event = {
            "at": _now(),
            "kind": str(kind),
            "title": str(title),
            "summary": str(summary),
            "severity": str(severity),
            "source": str(source),
            "dedupe_key": key,
            "evidence": evidence or {},
        }
        # State events should only reappear when the state actually changes.
        if kind.startswith("state_"):
            if self.state.get(key) == summary:
                return {"suppressed": True, **event}
            self.state[key] = summary
        self.data.setdefault("events", []).append(event)
        self.data["events"] = self.data["events"][-300:]
        self._save()
        return event

    def recent(self, limit: int = 40) -> list[Dict[str, Any]]:
        self._load()
        safe_limit = max(1, min(int(limit), 100))
        return list(reversed(self.data.get("events", [])[-safe_limit:]))

    def mark_seen(self, timestamp: str | None = None) -> None:
        self._load()
        self.state["last_seen_at"] = str(timestamp or _now())
        self._save()

    def unread_count(self) -> int:
        self._load()
        last_seen = str(self.state.get("last_seen_at") or "")
        if not last_seen:
            return len(self.data.get("events", []))
        return sum(1 for item in self.data.get("events", []) if str(item.get("at") or "") > last_seen)
